---
title: "Assn2"
output: html_document
date: '2022-10-25'
---

```{r setup, include=FALSE}
library(pacman)
p_load(pacman, devtools, bookdown, tidyverse, ggforce, flextable, latex2exp, png, magick, metafor, rmcorr, readr, forestplot)
install_github("daniel1noble/orchaRd", force = TRUE)
devtools::install_github("daniel1noble/orchaRd", force = TRUE)
library(orchaRd)
```

```{r}
clark <- read_csv('data/OA_activitydat_20190302_BIOL3207 (1).csv')
clark <- na.omit(clark)
clark <- clark %>% select(-loc, -comment, -...1)
summary_clark <- clark %>% group_by(species, treatment, size) %>% summarise(across(c(activity), funs(mean, se=sd(.)/sqrt(n()), n())))

CO2 <- summary_clark[summary_clark$treatment == 'CO2',]
control <- summary_clark[summary_clark$treatment == 'control',]
to_meta <- cbind(CO2, control)%>% select(-7, -2, -8, -9) %>% rename(Species = species...1, ctrl.n = activity_n...12, ctrl.sd = activity_se...11, ctrl.mean = activity_mean...10, oa.n = activity_n...6, oa.sd = activity_se...5, oa.mean = activity_mean...4, 'Life stage' = size...3)

to_meta$`Life stage`[to_meta$`Life stage`=='big'] <- 'Adult'
to_meta$`Life stage`[to_meta$`Life stage`=='small'] <- 'Juvenile'
```
```{r}
entry <- cbind(to_meta, read_csv('data/clark_paper_data.csv')) %>% rename(Life.stage = 'Life stage', Year..online. = 'Year (online)',Year..print. = 'Year (print)', Pub.year.IF = 'Pub year IF', X2017.IF = '2017 IF', Average.n = 'Average n', Effect.type = 'Effect type', Climate..FishBase. = 'Climate (FishBase)', Env.cue.stimulus. = 'Env cue/stimulus?', Behavioural.metric = 'Behavioural metric', Cue.stimulus.type = 'Cue/stimulus type') %>% select(-23)

metadata <- merge.data.frame(entry, read.csv('data/ocean_meta_data.csv'), all = TRUE)

```

```{r}
metadata <- escalc(measure = 'ROMC', m1i = ctrl.mean, m2i = oa.mean, sd1i = ctrl.sd, sd2i = oa.sd, ri = rep(0, 826), ni = Average.n, data = metadata, var.names = c('effect.size', 'sampling.variance'))
metadata = na.omit(metadata)
```
```{r}
MAM <- rma.mv(data = metadata, yi = effect.size, V = sampling.variance, random = list( ~1 | Study, ~1 | Behavioural.metric))
MAM
```
```{r}
predict(MAM, transf = "transf.ztor")

i2 <- orchaRd::i2_ml(MAM)
i2
```
```{r}
orchard_plot(data = metadata, object = MAM, group = 'Study', xlab = 'plplpl', mod = 1, angle = 0)
```
```{r}
funnel(x = metadata$effect.size, vi = metadata$sampling.variance, yaxis = 'vi',
    digits = 2, level = c(0.1, 0.05, 0.01), shade = c("white", "gray55", "gray 75"),
    las = 1, atransf = tanh, legend = TRUE)
```
```{r}
ggplot(metadata, aes(y = effect.size, x = Year..online., size = sampling.variance)) + geom_point(alpha = 0.3) +
    geom_smooth(method = lm, col = "red", show.legend = FALSE) + labs(x = "Publication Year",
    y = "Fisher's Z-transformed Correlation Coefficient (Zr)", size = "variance")
```
```{r}
MAMlag <- rma.mv(effect.size ~ Year..online., V = sampling.variance, random = list(~1 | Study, ~1 | Behavioural.metric), test = "t", dfs = "contain", data = metadata)
summary(MAMlag)

MAMfile <- metareg_time <- rma.mv(effect.size ~ Year..online. + sampling.variance, V = sampling.variance, random = list(~1 | Study, ~1 | Behavioural.metric),test = "t", dfs = "contain", data = metadata)

MAMlag
MAMfile
```
